version: "3.8"
services:
  database:
    image: "postgres:13"
    container_name: fishapp-database
    restart: on-failure
    ports:
      - "5432"
    environment:
      # Excluded vars below are automatically defined by PSQL
      #POSTGRES_DB: ${DB_NAME}
      #POSTGRES_USER: ${DB_USER}
      # FIXME: USE SECRETS!
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWD:?Err DB admin password is not set! Run ./generate.sh to generate}
      DB_NAME: ${DB_NAME:?Err Name of database must be set.}
      DB_USER: ${DB_USER:?Err User to create must be set}
      DB_PASSWD: ${DB_PASSWD:?Err Password for user is missing.}
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./scripts/db_init
        target: /docker-entrypoint-initdb.d

  api:
    container_name: fishapp-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    expose:
      - "8080"
    depends_on:
      - "database"
    environment:
      COMPOSE_DB_HOST: fishapp-database
      COMPOSE_DB_BASE: ${DB_NAME:?Err Server must have configured an database!}
      COMPOSE_DB_USER: ${DB_USER:?Err Server must have configured a database user.}
      COMPOSE_DB_PASSWD: ${DB_PASSWD:?Err Unable to get database password. Server halted.}
    labels:
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=Host(`${API_TLD}`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=buypass"
    volumes:
      - payara-images:/opt/payara/images

  reverse-proxy:
    container_name: fishapp-proxy
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # Front ports (must have 80 for ACME protocol)
      - "80:80"
      - "443:443"
    #environment:
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # TODO: Use secrets to improve security
      - ${PWD}/config/traefik/cert.json:/acme.json
      - ${PWD}/config/traefik/config.toml:/traefik.toml

volumes:
  database-data:
  payara-images:
