version: "3.8"
services:
  database:
    image: "postgres:13"
    container_name: fishapp-database
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      # Excluded vars below are automatically defined by PSQL
      #POSTGRES_DB: ${DB_NAME}
      #POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWD:?Err DB admin password is not set! Run ./start.sh to generate}
      DB_NAME: ${DB_NAME:?Err Name of database must be set.}
      DB_USER: ${DB_USER:?Err User to create must be set}
      DB_PASSWD: ${DB_PASSWD:?Err Password for user is missing.}
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./scripts/db_init
        target: /docker-entrypoint-initdb.d

  api:
    container_name: fishapp-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
    volumes:
      - type: volume
        source: payara-images
        target: /opt/payara/images
    #      - type: bind
    #        source: ./config/payara_config_files
    #        target: /opt/payara/payara_config_files
    depends_on:
      - "database"
    environment:
      #POSTBOOT_COMMANDS: /opt/payara/payara_config_files/preboot_commands.asadmin
      COMPOSE_DB_HOST: fishapp-database
      COMPOSE_DB_BASE: ${DB_NAME:?Err Server must have configured an database!}
      COMPOSE_DB_USER: ${DB_USER:?Err Server must have configured a database user.}
      COMPOSE_DB_PASSWD: ${DB_PASSWD:?Err Unable to get database password. Server halted.}
      # Only in use with full Payara Server FIXME: Unsure if working
      #PAYARA_MASTERPASS: ${PAYARA_MASTERPASS:? The Payara Server UI is missing a password.}
    labels:
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=2000000"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=2000000"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.middlewares=api-add-prefix@docker"
      - "traefik.http.middlewares.api-add-prefix.addprefix.prefix=/api"

  reverse-proxy:
    container_name: fishapp-proxy
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8088:8080" # 8088 on localhost

    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=2000000"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=2000000"
volumes:
  database-data:
  payara-images:
