[accessLog]

[api]
insecure = true
dashboard = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"

[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

# Now this works, but for loose coupling
# fix this using variables in the future
[certificatesResolvers.buypass.acme]
email = "abuse@gaupne.net"
storage = "acme.json"
caServer = "https://api.buypass.com/acme/directory"

[certificatesResolvers.buypass.acme.httpChallenge]
entryPoint = "web"
