apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: fishapp
    service: auth
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: fishapp
spec:
  selector:
    matchLabels:
      app: fishapp
      service: auth
  template:
    metadata:
      labels:
        app: fishapp
        service: auth
    spec:
      volumes:
        - name: jwt-pubkey-volume
          persistentVolumeClaim:
            claimName: jwt-pubkey-pvc
      containers:
        - name: auth-container
          volumeMounts:
            - mountPath: /aplication_storage/token_key
              name: jwt-pubkey-volume
          imagePullPolicy: Never
          image: fishapp-auth:latest
          ports:
            - containerPort: 80
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:80/"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5 # todo:change to 1
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5 # todo:change to 1
