apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  selector:
    app: fishapp
    service: store
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: fishapp
spec:
  selector:
    matchLabels:
      app: fishapp
      service: store
  template:
    metadata:
      labels:
        app: fishapp
        service: store
    spec:
      containers:
        - name: auth-store
          imagePullPolicy: Always
          image: localhost:32000/fishapp-store:latest
          ports:
            - containerPort: 9080
            - containerPort: 9443
          envFrom:
            - secretRef:
                name: inter-container-logins-secrets
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:80/"
            - name: MEDIA_SERVICE_URL
              value: "http://media-service:80/"
            - name: CHECKOUT_SERVICE_URL
              value: "http://checkout-service:80/"
            - name: STORE_SERVICE_URL
              value: "http://store-service:80/"
          readinessProbe: # todo:change to prod values
            httpGet:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe: # todo:change to prod values
            httpGet:
              path: /health/live
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5