apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: fishapp
    service: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: fishapp
spec:
  selector:
    matchLabels:
      app: fishapp
      service: frontend
  template:
    metadata:
      labels:
        app: fishapp
        service: frontend
    spec:
      containers:
        - name: auth-frontend
          imagePullPolicy: Always
          image: localhost:32000/fishapp-frontend:latest
          ports:
            - containerPort: 9080
            - containerPort: 9443
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:80/"
            - name: REACT_APP_HOST_URL
              value: "http://fishapp.no:80/"
          readinessProbe: # todo:change to prod values
            httpGet:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe: # todo:change to prod values
            httpGet:
              path: /health/live
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5