apiVersion: v1
kind: Service
metadata:
  name: fishapp-db
spec:
  selector:
    app: fishapp
    service: dev-db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: fishapp-db-dev-nodeport
spec:
  type: NodePort
  selector:
    app: fishapp
    service: dev-db
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-db
  labels:
    app: fishapp
spec:
  selector:
    matchLabels:
      app: fishapp
      service: dev-db
  template:
    metadata:
      labels:
        app: fishapp
        service: dev-db
    spec:
      containers:
        - name: dev-db-container
          # imagePullPolicy: Never
          image: localhost:32000/fishapp-dev-db:latest
          ports:
            - containerPort: 80
---

